name: ci

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: DEVSECOPS-TS-SCI/DEMOS/demo-02-containerized-python-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Lint
        run: |
          python -m ruff check .

      - name: Tests
        run: |
          python -m pytest -q

      - name: Dependency audit (SCA)
        continue-on-error: true
        run: |
          python -m pip_audit -r requirements.txt --progress-spinner off

      - name: Bandit (SAST)
        continue-on-error: true
        run: |
          python -m bandit -q -r src
